title: Syn Naulaid
description: Personal Page
baseurl: ""
url: "https://synnaulaid.github.io"
markdown: kramdown
permalink: /:title/
future: true

plugins:
  - jekyll-redirect-from
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/blog/:num/'  
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true   
  trail:
    before: 2
    after: 2 