title: Syn Naulaid
description: Personal Page
baseurl: ""
url: "https://synnaulaid.github.io"
markdown: kramdown
permalink: /:title/
future: true

paginate: 1 # default 5-10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-redirect-from
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 1
  permalink: "/blog/page:num/"
  title: "Blog - page :num"
  short_fields: 'date'
  short_reverse: true

