title: Syn Naulaid
description: Personal Page
baseurl: ""
url: "https://synnaulaid.github.io"
markdown: kramdown
permalink: /:title/
future: true

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
